name:                improg
version:             0.1.0.0
github:              "/"
license:             BSD3
author:              "S. Haller, O. Katz, L. Ljubuncic, A. Richard, I. Suslov"
maintainer:          "example@example.com"
copyright:           "2022 S. Haller, O. Katz, L. Ljubuncic, A. Richard, I. Suslov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab2 at <https://gitlab2.cip.ifi.lmu.de/richard/improg-f>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  improg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - improg

tests:
  improg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - improg
